version: "3.9"
services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - '.:/var/www/current/'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/sites/:/etc/nginx/sites-available'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'
    links:
      - php

  php:
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - '.:/var/www/current/'
    working_dir: '/var/www/current'
